name: Native

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build_native:
    name: Cross build with Scala Native
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            name: linux
            ext: so
# TODO This works, but binary signing and notarization is required
#          - os: macos-latest
#            arch: arm64
#            name: mac
# TODO It seems arm64 is not available yet (2024-11)
#          - os: ubuntu-latest
#            arch: arm64
#            name: linux
# TODO Need some tweaks to run sbt on Windows
#          - os: windows-latest
#            arch: x64
#            name: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wvlet/wvlet
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: sbt
      - name: Set SCALA_VERSION env
        run: |
          SCALA_VERSION=$(cat SCALA_VERSION)
          echo SCALA_VERSION: $SCALA_VERSION
          echo "SCALA_VERSION=$SCALA_VERSION" >> $GITHUB_ENV
      - name: Build native binary for ${{ matrix.name }}-${{ matrix.arch }}
        run: |
          ./sbt 'wvcLib/nativeLink'
          ls -alFh wvc/target/scala-${{ env.SCALA_VERSION }}
          FILEPATH=$(find . -name libwvlet.so)
          cp $(find . -name libwvlet.${{ matrix.ext }}) \
          libwvlet_${{ matrix.name }}-${{ matrix.arch }}.${{ matrix.ext }}
      - name: Upload native library for ${{ matrix.name }}-${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: libwvlet_${{ matrix.name }}-${{ matrix.arch }}.${{ matrix.ext }}
          path: libwvlet_${{ matrix.name }}-${{ matrix.arch }}.${{ matrix.ext }}
      - name: Upload Libraries Release
        if: ${{ github.event_name == 'release' }}
        shell: bash
        run: |
          for file in ./libwvlet_*; do
            echo "Uploading $file"
            gh release upload ${{ github.event.release.tag_name }} "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  collect_artifact:
    name: Collect wvc binaries
    runs-on: ubuntu-latest
    needs: build_native
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wvc-binaries
          delete-merged: true
